### ISSUE TITLE
Unable to decide some characters on windows

### ISSUE THREAD

**Issue by Joetib** [nextblu/shellbin#5]
I am not sure if the problem pertains to only windows and whether this is an issue from V or the server.
However when the tool is run against the windows command 'tree' as
```
tree | shellbin
```
The server response returns error saying it is unable to decide the characters that the terminal uses to build lines connecting the directories.
(I'm sorry for my terminology)

**Comment by MattiaFailla** [comment]
Fixed: https://shellbin.nextblu.com/#/WK24AQV1UA

**Comment by Joetib** [comment]
That's great
