### ISSUE TITLE
Text indentation is not honoured and line breaks on comma on webpage

### ISSUE THREAD

**Issue by Joetib** [nextblu/shellbin#6]
When a terminal output has indentations, the resultant shellbin created does not honour this indentation.
Also if a line in the terminal output contains a comma, and is sent to the server, on the website, the bin breaks the comma separated content into multiple lines instead of being on one line. I'm not sure if this error should be reported here or there's another repository for it.

**Comment by MattiaFailla** [comment]
Thank you so much for reporting the problem. You can find the source code of the server here: [ShellBin-server](https://github.com/nextblu/shellbin-server). And the source code for the web-app here: [ShellBin-web](https://github.com/nextblu/shellbin-web). I opened an issue there too so I can track the problem.

I am currently trying to hand-implement a way for client to process stdin. I will post more updates here.

**Comment by MattiaFailla** [comment]
Fixed: https://shellbin.nextblu.com/#/WK24AQV1UA

**Comment by Joetib** [comment]
Whoaa, you're fast. That's cool
